spring:
  r2dbc:
    url: r2dbc:h2:mem:///grndb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:grndb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

server:
  port: 8080
logging:
  level:
    root: INFO
