CREATE TABLE cell_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_name VARCHAR(255),
    gene_expression_x DOUBLE,
    gene_expression_y DOUBLE,
    potential_value DOUBLE,
    cell_type VARCHAR(255),
    simulation_run_id BIGINT
);
